### ISSUE TITLE
A few requests for helping downstream packaging

### ISSUE THREAD

**Issue by LecrisUT** [andrewhickman/prost-reflect#160]
### Moving the tests to specific `tests` folder

Currently there are places where `mod tests` is being called in the source
https://github.com/andrewhickman/prost-reflect/blob/cca111af6e13dda357798adea287b94b56d3ae64/prost-reflect/src/descriptor/mod.rs#L6-L7
but the `tests.rs` files are not included in the crate. This leads to compilation issues when trying to compile and run other test sources like the doc tests.

Of course having the tests included would also be appreciated and it would help us cover more infrastructures, like `s390x`.

### `LICENSE-*` in prost-reflect-0.15.1 were not expanded

This is probably due to the system where the crates were published from was a windows system without symlink setup. Instead the contents of the files is just  literal `../LICENSE-APACHE` text. A similar issue, it seems the line-ending format of `README.md` changed from `LF` to windows specific `CRLF`, probably due to a similar issue (maybe due to the `generate-readme.ps1`, that should be straightforward to convert to a python script if you want it os independent). 

This we can fix on our end for this specific release.

More generally though, you could consider adding a CD workflow like
```yaml
on:
  push:
    tags: ["v*.*.*"]

jobs:
  publish-crate:
    name: Publish crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
```
There are various other workflows you can check for inspiration [^1]

But also it would also probably be enough to be aware of this issue.

[^1]: https://github.com/ratatui/ratatui/blob/main/.github/workflows/release-stable.yml

### Test failure on i686

When we run this test
https://github.com/andrewhickman/prost-reflect/blob/cca111af6e13dda357798adea287b94b56d3ae64/prost-reflect/src/dynamic/mod.rs#L1198-L1202
It fails on i686. We think this is expected failure, but we want to confirm it with you. We currently ignore this test, but do you think it's something useful to track in downstream tests as well, or is it mostly useful for development?
